const dinosaurs = [
	{
		name: "Brachiosaurus",
		group: "Large Sauropods",
		group_letter: "A",
		card_number: 1,
		random_fact: "Tallest neck in dino history.",
		number_eggs: 12,
		territorial_range: 1500,
		iq: 3,
		years: 148,
		length: 25,
		height: 15,
		weight: 80000,
		number_skeletons: 10,
		number_teeth: 56,
		speed: 5,
		footprint: 60,
		nest_size: 300,
		tooth_size: 20,
		bite_force: 60000,
		egg_size: 20,
		brain_size: 300,
		jaw_size: 150,
		encephalization: 0.2,
	},
	{
		name: "Amargasaurus",
		group: "Large Sauropods",
		group_letter: "A",
		card_number: 2,
		random_fact: "Showcased a distinctive double-sail feature.",
		number_eggs: 8,
		territorial_range: 800,
		iq: 2,
		years: 135,
		length: 9,
		height: 4,
		weight: 2000,
		number_skeletons: 3,
		number_teeth: 24,
		speed: 3,
		footprint: 30,
		nest_size: 120,
		tooth_size: 10,
		bite_force: 15000,
		egg_size: 10,
		brain_size: 50,
		jaw_size: 40,
		encephalization: 0.1,
	},
	{
		name: "Diplodocus",
		group: "Large Sauropods",
		group_letter: "A",
		card_number: 3,
		random_fact: "Possessed a tail capable of sonic cracks.",
		number_eggs: 10,
		territorial_range: 1000,
		iq: 2,
		years: 154,
		length: 27,
		height: 10,
		weight: 6000,
		number_skeletons: 8,
		number_teeth: 48,
		speed: 4,
		footprint: 40,
		nest_size: 180,
		tooth_size: 15,
		bite_force: 30000,
		egg_size: 15,
		brain_size: 80,
		jaw_size: 70,
		encephalization: 0.15,
	},
	{
		name: "Argentinosaurus",
		group: "Large Sauropods",
		group_letter: "A",
		card_number: 4,
		random_fact: "Weightier than multiple elephants combined.",
		number_eggs: 15,
		territorial_range: 2000,
		iq: 1,
		years: 96,
		length: 35,
		height: 18,
		weight: 90000,
		number_skeletons: 5,
		number_teeth: 60,
		speed: 2,
		footprint: 70,
		nest_size: 250,
		tooth_size: 25,
		bite_force: 75000,
		egg_size: 25,
		brain_size: 30,
		jaw_size: 120,
		encephalization: 0.05,
	},

	{
		name: "Tyrannosaurusrex",
		group: "Big Predatory Theropods",
		group_letter: "B",
		card_number: 1,
		random_fact: "Armed with banana-sized teeth and a terrifying bite.",
		number_eggs: 10,
		territorial_range: 500,
		iq: 5,
		years: 68,
		length: 12,
		height: 4.5,
		weight: 9000,
		number_skeletons: 20,
		number_teeth: 60,
		speed: 25,
		footprint: 40,
		nest_size: 120,
		tooth_size: 15,
		bite_force: 60000,
		egg_size: 12,
		brain_size: 100,
		jaw_size: 70,
		encephalization: 0.3,
	},
	{
		name: "Baryonyx",
		group: "Big Predatory Theropods",
		group_letter: "B",
		card_number: 2,
		random_fact: "Specialized in a diet of fresh fish.",
		number_eggs: 8,
		territorial_range: 300,
		iq: 4,
		years: 125,
		length: 10,
		height: 3.5,
		weight: 2000,
		number_skeletons: 5,
		number_teeth: 32,
		speed: 20,
		footprint: 30,
		nest_size: 100,
		tooth_size: 12,
		bite_force: 30000,
		egg_size: 10,
		brain_size: 70,
		jaw_size: 50,
		encephalization: 0.25,
	},
	{
		name: "Allosaurus",
		group: "Big Predatory Theropods",
		group_letter: "B",
		card_number: 3,
		random_fact: "Stood as the star predator of the Jurassic era.",
		number_eggs: 12,
		territorial_range: 400,
		iq: 3,
		years: 155,
		length: 9,
		height: 3,
		weight: 1500,
		number_skeletons: 15,
		number_teeth: 40,
		speed: 30,
		footprint: 25,
		nest_size: 80,
		tooth_size: 10,
		bite_force: 40000,
		egg_size: 8,
		brain_size: 60,
		jaw_size: 45,
		encephalization: 0.2,
	},
	{
		name: "Spinosaurus",
		group: "Big Predatory Theropods",
		group_letter: "B",
		card_number: 4,
		random_fact: "Sported a sail-like structure and was an agile swimmer.",
		number_eggs: 15,
		territorial_range: 600,
		iq: 4,
		years: 95,
		length: 15,
		height: 6,
		weight: 7000,
		number_skeletons: 10,
		number_teeth: 48,
		speed: 22,
		footprint: 35,
		nest_size: 110,
		tooth_size: 14,
		bite_force: 45000,
		egg_size: 14,
		brain_size: 80,
		jaw_size: 60,
		encephalization: 0.25,
	},

	{
		name: "Pteranodon",
		group: "Flyers",
		group_letter: "C",
		card_number: 1,
		random_fact: "Ruled the skies with an impressive wingspan.",
		number_eggs: 2,
		territorial_range: 150,
		iq: 2,
		years: 88,
		length: 7,
		height: 2,
		weight: 25,
		number_skeletons: 10,
		number_teeth: 0,
		speed: 70,
		footprint: 0,
		nest_size: 20,
		tooth_size: 0,
		bite_force: 0,
		egg_size: 10,
		brain_size: 20,
		jaw_size: 0,
		encephalization: 0.1,
	},
	{
		name: "Quetzalcoatlus",
		group: "Flyers",
		group_letter: "C",
		card_number: 2,
		random_fact: "Earned the title of the largest flying reptile.",
		number_eggs: 3,
		territorial_range: 200,
		iq: 2,
		years: 66,
		length: 10,
		height: 3.5,
		weight: 75,
		number_skeletons: 5,
		number_teeth: 0,
		speed: 80,
		footprint: 0,
		nest_size: 25,
		tooth_size: 0,
		bite_force: 0,
		egg_size: 12,
		brain_size: 30,
		jaw_size: 0,
		encephalization: 0.15,
	},
	{
		name: "Archaeopteryx",
		group: "Flyers",
		group_letter: "C",
		card_number: 3,
		random_fact: "Pioneered as one of the earliest-known birds.",
		number_eggs: 4,
		territorial_range: 30,
		iq: 3,
		years: 155,
		length: 0.5,
		height: 0.3,
		weight: 0.5,
		number_skeletons: 12,
		number_teeth: 12,
		speed: 10,
		footprint: 5,
		nest_size: 5,
		tooth_size: 1,
		bite_force: 10,
		egg_size: 2,
		brain_size: 2,
		jaw_size: 3,
		encephalization: 0.05,
	},
	{
		name: "Dimorphodon",
		group: "Flyers",
		group_letter: "C",
		card_number: 4,
		random_fact: "Boasted double rows of dagger-like teeth.",
		number_eggs: 3,
		territorial_range: 40,
		iq: 2,
		years: 148,
		length: 1.5,
		height: 0.5,
		weight: 3,
		number_skeletons: 8,
		number_teeth: 20,
		speed: 30,
		footprint: 10,
		nest_size: 8,
		tooth_size: 2,
		bite_force: 15,
		egg_size: 4,
		brain_size: 5,
		jaw_size: 5,
		encephalization: 0.08,
	},
	{
		name: "Parasaurolophus",
		group: "Hadrosaurs",
		group_letter: "D",
		card_number: 1,
		random_fact: "Known for its head crest, possibly for communication.",
		number_eggs: 10,
		territorial_range: 500,
		iq: 3,
		years: 70,
		length: 10,
		height: 4,
		weight: 3000,
		number_skeletons: 15,
		number_teeth: 800,
		speed: 30,
		footprint: 40,
		nest_size: 120,
		tooth_size: 5,
		bite_force: 1500,
		egg_size: 10,
		brain_size: 50,
		jaw_size: 40,
		encephalization: 0.1,
	},
	{
		name: "Corythosaurus",
		group: "Hadrosaurs",
		group_letter: "D",
		card_number: 2,
		random_fact: "A distinguished duck-billed dinosaur from Canada.",
		number_eggs: 8,
		territorial_range: 400,
		iq: 2,
		years: 75,
		length: 8,
		height: 3,
		weight: 2000,
		number_skeletons: 10,
		number_teeth: 600,
		speed: 25,
		footprint: 30,
		nest_size: 100,
		tooth_size: 4,
		bite_force: 1200,
		egg_size: 8,
		brain_size: 40,
		jaw_size: 35,
		encephalization: 0.09,
	},
	{
		name: "Edmontosaurus",
		group: "Hadrosaurs",
		group_letter: "D",
		card_number: 3,
		random_fact: "A herbivore with a vast array of grinding teeth.",
		number_eggs: 12,
		territorial_range: 600,
		iq: 3,
		years: 68,
		length: 12,
		height: 4.5,
		weight: 3500,
		number_skeletons: 12,
		number_teeth: 700,
		speed: 28,
		footprint: 35,
		nest_size: 110,
		tooth_size: 6,
		bite_force: 1400,
		egg_size: 12,
		brain_size: 60,
		jaw_size: 45,
		encephalization: 0.11,
	},
	{
		name: "Lambeosaurus",
		group: "Hadrosaurs",
		group_letter: "D",
		card_number: 4,
		random_fact: "Featuring a unique, hollow-headed appearance.",
		number_eggs: 9,
		territorial_range: 450,
		iq: 2,
		years: 72,
		length: 9,
		height: 3.2,
		weight: 2500,
		number_skeletons: 8,
		number_teeth: 500,
		speed: 26,
		footprint: 32,
		nest_size: 105,
		tooth_size: 4.5,
		bite_force: 1300,
		egg_size: 9,
		brain_size: 45,
		jaw_size: 38,
		encephalization: 0.09,
	},

	{
		name: "Ichthyosaurus",
		group: "Swimmers",
		group_letter: "E",
		card_number: 1,
		random_fact: "An aquatic reptile known for its streamlined design.",
		number_eggs: 6,
		territorial_range: 150,
		iq: 2,
		years: 100,
		length: 4,
		height: 1.5,
		weight: 500,
		number_skeletons: 15,
		number_teeth: 80,
		speed: 40,
		footprint: 0,
		nest_size: 0,
		tooth_size: 3,
		bite_force: 500,
		egg_size: 6,
		brain_size: 15,
		jaw_size: 20,
		encephalization: 0.05,
	},
	{
		name: "Mosasaurus",
		group: "Swimmers",
		group_letter: "E",
		card_number: 2,
		random_fact: "A sea serpent equipped with fearsome jaws.",
		number_eggs: 4,
		territorial_range: 200,
		iq: 3,
		years: 68,
		length: 15,
		height: 6,
		weight: 3000,
		number_skeletons: 10,
		number_teeth: 100,
		speed: 50,
		footprint: 0,
		nest_size: 0,
		tooth_size: 5,
		bite_force: 1000,
		egg_size: 8,
		brain_size: 30,
		jaw_size: 40,
		encephalization: 0.07,
	},
	{
		name: "Plesiosaurus",
		group: "Swimmers",
		group_letter: "E",
		card_number: 3,
		random_fact: "Shares a family resemblance with the Loch Ness legend.",
		number_eggs: 6,
		territorial_range: 180,
		iq: 2,
		years: 85,
		length: 6,
		height: 2.5,
		weight: 800,
		number_skeletons: 8,
		number_teeth: 60,
		speed: 30,
		footprint: 0,
		nest_size: 0,
		tooth_size: 4,
		bite_force: 800,
		egg_size: 7,
		brain_size: 20,
		jaw_size: 25,
		encephalization: 0.06,
	},
	{
		name: "Nothosaurus",
		group: "Swimmers",
		group_letter: "E",
		card_number: 4,
		random_fact: "Mastered the art of sleek swimming.",
		number_eggs: 5,
		territorial_range: 120,
		iq: 2,
		years: 110,
		length: 4.5,
		height: 1.8,
		weight: 600,
		number_skeletons: 6,
		number_teeth: 40,
		speed: 25,
		footprint: 0,
		nest_size: 0,
		tooth_size: 3.5,
		bite_force: 600,
		egg_size: 5,
		brain_size: 18,
		jaw_size: 22,
		encephalization: 0.05,
	},
	{
		name: "Stegosaurus",
		group: "Armored Dinosaurs",
		group_letter: "F",
		card_number: 1,
		random_fact: "Famous for its bony plates and spiked tail.",
		number_eggs: 10,
		territorial_range: 300,
		iq: 2,
		years: 155,
		length: 9,
		height: 4,
		weight: 3500,
		number_skeletons: 20,
		number_teeth: 112,
		speed: 12,
		footprint: 40,
		nest_size: 120,
		tooth_size: 5,
		bite_force: 1500,
		egg_size: 10,
		brain_size: 40,
		jaw_size: 30,
		encephalization: 0.08,
	},
	{
		name: "Ankylosaurus",
		group: "Armored Dinosaurs",
		group_letter: "F",
		card_number: 2,
		random_fact: "Possessed formidable armor and a tail club.",
		number_eggs: 8,
		territorial_range: 250,
		iq: 2,
		years: 68,
		length: 7,
		height: 2.5,
		weight: 3000,
		number_skeletons: 12,
		number_teeth: 64,
		speed: 10,
		footprint: 30,
		nest_size: 100,
		tooth_size: 4,
		bite_force: 1200,
		egg_size: 8,
		brain_size: 35,
		jaw_size: 25,
		encephalization: 0.07,
	},
	{
		name: "Sauropelta",
		group: "Armored Dinosaurs",
		group_letter: "F",
		card_number: 3,
		random_fact: "An armored dinosaur equipped with a bony shield.",
		number_eggs: 6,
		territorial_range: 200,
		iq: 2,
		years: 110,
		length: 6.5,
		height: 2.8,
		weight: 2000,
		number_skeletons: 8,
		number_teeth: 40,
		speed: 8,
		footprint: 35,
		nest_size: 80,
		tooth_size: 3,
		bite_force: 800,
		egg_size: 6,
		brain_size: 30,
		jaw_size: 20,
		encephalization: 0.06,
	},
	{
		name: "Kentrosaurus",
		group: "Armored Dinosaurs",
		group_letter: "F",
		card_number: 4,
		random_fact: "Showcased a back adorned with spikes.",
		number_eggs: 8,
		territorial_range: 180,
		iq: 2,
		years: 125,
		length: 5.5,
		height: 2.2,
		weight: 1500,
		number_skeletons: 10,
		number_teeth: 48,
		speed: 15,
		footprint: 28,
		nest_size: 90,
		tooth_size: 4,
		bite_force: 1000,
		egg_size: 7,
		brain_size: 25,
		jaw_size: 18,
		encephalization: 0.05,
	},
	{
		name: "Velociraptor",
		group: "Small Theropods",
		group_letter: "G",
		card_number: 1,
		random_fact: "A small yet intelligent and lethal predator.",
		number_eggs: 10,
		territorial_range: 50,
		iq: 50,
		years: 75,
		length: 2,
		height: 0.8,
		weight: 70,
		number_skeletons: 12,
		number_teeth: 80,
		speed: 40,
		footprint: 10,
		nest_size: 30,
		tooth_size: 3,
		bite_force: 500,
		egg_size: 5,
		brain_size: 20,
		jaw_size: 15,
		encephalization: 0.4,
	},
	{
		name: "Gallimimus",
		group: "Small Theropods",
		group_letter: "G",
		card_number: 2,
		random_fact: "Renowned for its speed and bird-like features.",
		number_eggs: 12,
		territorial_range: 80,
		iq: 45,
		years: 70,
		length: 4,
		height: 2,
		weight: 200,
		number_skeletons: 8,
		number_teeth: 60,
		speed: 60,
		footprint: 20,
		nest_size: 40,
		tooth_size: 2,
		bite_force: 300,
		egg_size: 6,
		brain_size: 15,
		jaw_size: 12,
		encephalization: 0.35,
	},
	{
		name: "Oviraptor",
		group: "Small Theropods",
		group_letter: "G",
		card_number: 3,
		random_fact: "Misnamed, as it likely didn't steal eggs.",
		number_eggs: 8,
		territorial_range: 40,
		iq: 40,
		years: 68,
		length: 2.5,
		height: 1,
		weight: 50,
		number_skeletons: 6,
		number_teeth: 40,
		speed: 30,
		footprint: 8,
		nest_size: 25,
		tooth_size: 1.5,
		bite_force: 200,
		egg_size: 4,
		brain_size: 10,
		jaw_size: 8,
		encephalization: 0.3,
	},
	{
		name: "Dilophosaurus",
		group: "Small Theropods",
		group_letter: "G",
		card_number: 4,
		random_fact: "An early Jurassic marvel with twin crests.",
		number_eggs: 6,
		territorial_range: 60,
		iq: 35,
		years: 150,
		length: 6,
		height: 2,
		weight: 150,
		number_skeletons: 10,
		number_teeth: 50,
		speed: 35,
		footprint: 15,
		nest_size: 35,
		tooth_size: 2.5,
		bite_force: 250,
		egg_size: 5,
		brain_size: 12,
		jaw_size: 10,
		encephalization: 0.28,
	},
	{
		name: "Triceratops",
		group: "Ceratopsians and Co.",
		group_letter: "H",
		card_number: 1,
		random_fact: "Boasted a three-horned face-off strategy.",
		number_eggs: 12,
		territorial_range: 200,
		iq: 4,
		years: 66,
		length: 8,
		height: 3.5,
		weight: 9000,
		number_skeletons: 15,
		number_teeth: 800,
		speed: 20,
		footprint: 30,
		nest_size: 100,
		tooth_size: 6,
		bite_force: 1500,
		egg_size: 10,
		brain_size: 40,
		jaw_size: 30,
		encephalization: 0.1,
	},
	{
		name: "Styracosaurus",
		group: "Ceratopsians and Co.",
		group_letter: "H",
		card_number: 2,
		random_fact: "Distinguished by its nasal horn and head spikes.",
		number_eggs: 10,
		territorial_range: 180,
		iq: 3,
		years: 70,
		length: 5.5,
		height: 2.5,
		weight: 3000,
		number_skeletons: 10,
		number_teeth: 400,
		speed: 15,
		footprint: 25,
		nest_size: 80,
		tooth_size: 4,
		bite_force: 1200,
		egg_size: 8,
		brain_size: 35,
		jaw_size: 25,
		encephalization: 0.08,
	},
	{
		name: "Pachycephalosaurus",
		group: "Ceratopsians and Co.",
		group_letter: "H",
		card_number: 3,
		random_fact: "Engaged in head-butting contests.",
		number_eggs: 8,
		territorial_range: 100,
		iq: 2,
		years: 68,
		length: 4,
		height: 2,
		weight: 1000,
		number_skeletons: 6,
		number_teeth: 60,
		speed: 25,
		footprint: 15,
		nest_size: 40,
		tooth_size: 3,
		bite_force: 800,
		egg_size: 6,
		brain_size: 25,
		jaw_size: 20,
		encephalization: 0.06,
	},
	{
		name: "Protoceratops",
		group: "Ceratopsians and Co.",
		group_letter: "H",
		card_number: 4,
		random_fact: "A petite herbivore adorned with a frill.",
		number_eggs: 6,
		territorial_range: 80,
		iq: 2,
		years: 75,
		length: 2.5,
		height: 1.2,
		weight: 300,
		number_skeletons: 8,
		number_teeth: 100,
		speed: 10,
		footprint: 10,
		nest_size: 20,
		tooth_size: 2,
		bite_force: 400,
		egg_size: 4,
		brain_size: 15,
		jaw_size: 12,
		encephalization: 0.05,
	},
];

export default dinosaurs;
